import {
  Shield,
  Sword,
  BookOpen,
  Heart,
  Star,
  Globe,
  Users,
  Zap,
  Calendar,
  MapPin,
  Target,
  Brain,
} from "lucide-react";
import { CharacterTemplate } from "../type/TemplateMap";

export const CHARACTER_BASICINFO_TEMPLATES: CharacterTemplate = {
  basic: [
    {
      key: "race",
      label: "종족",
      icon: Globe,
      color: "bg-green-100 text-green-700",
      defaultValue: "인간",
      popular: true,
    },
    {
      key: "gender",
      label: "성별",
      icon: Users,
      color: "bg-pink-100 text-pink-700",
      defaultValue: "남성",
      popular: true,
    },
    {
      key: "age",
      label: "나이",
      icon: Calendar,
      color: "bg-yellow-100 text-yellow-700",
      defaultValue: "20세",
      popular: true,
    },
    {
      key: "birthplace",
      label: "출생지",
      icon: MapPin,
      color: "bg-purple-100 text-purple-700",
      defaultValue: "알 수 없음",
      popular: false,
    },
  ],
  attributes: [
    {
      key: "strength",
      label: "근력",
      icon: Sword,
      color: "bg-red-100 text-red-700",
      defaultValue: "보통",
      popular: true,
    },
    {
      key: "dexterity",
      label: "민첩",
      icon: Target,
      color: "bg-orange-100 text-orange-700",
      defaultValue: "보통",
      popular: true,
    },
    {
      key: "intelligence",
      label: "지능",
      icon: Brain,
      color: "bg-indigo-100 text-indigo-700",
      defaultValue: "보통",
      popular: true,
    },
    {
      key: "charisma",
      label: "매력",
      icon: Star,
      color: "bg-amber-100 text-amber-700",
      defaultValue: "보통",
      popular: false,
    },
    {
      key: "endurance",
      label: "체력",
      icon: Shield,
      color: "bg-emerald-100 text-emerald-700",
      defaultValue: "보통",
      popular: false,
    },
  ],
  background: [
    {
      key: "occupation",
      label: "직업",
      icon: BookOpen,
      color: "bg-teal-100 text-teal-700",
      defaultValue: "모험가",
      popular: true,
    },
    {
      key: "alignment",
      label: "성향",
      icon: Heart,
      color: "bg-rose-100 text-rose-700",
      defaultValue: "중립 선",
      popular: true,
    },
    {
      key: "affiliation",
      label: "소속",
      icon: Users,
      color: "bg-cyan-100 text-cyan-700",
      defaultValue: "없음",
      popular: false,
    },
    {
      key: "skills",
      label: "특기",
      icon: Zap,
      color: "bg-sky-100 text-sky-700",
      defaultValue: "검술",
      popular: false,
    },
  ],
};
